/** Mensajes de error de API visibles para el usuario (es-PE). */
export const ApiErrors = {
  NOT_AUTHENTICATED: 'No autenticado',
  FORBIDDEN: 'Acceso denegado',
  FORBIDDEN_ORG: 'No tienes permiso para esta empresa',
  UNKNOWN: 'Error desconocido',
  UNAUTHORIZED: 'No autorizado',
  MISSING_CUSTOMER_ID: 'Falta el identificador de la empresa',
  MISSING_DATE: 'Falta la fecha',
  MISSING_USER_OR_ORG: 'Faltan usuario o empresa',
  MISSING_REQUIRED_FIELDS: 'Faltan campos obligatorios',
  MISSING_NAME_OR_CODE: 'Faltan nombre o código',
  MISSING_ORG_ID: 'Falta la empresa',
  MISSING_INVITATION_ID: 'Falta el id de la invitación',
  MISSING_TOKEN: 'Falta el token',
  MISSING_INVITE_FIELDS: 'Faltan token, nombre, apellido o contraseña',
  MISSING_EMAIL_ORG_ROLE: 'Faltan correo, empresa o rol',
  INVALID_EMAIL: 'Ingresa un correo electrónico válido',
  MISSING_ORG_OR_USERS: 'Faltan empresa o usuarios',
  USER_NOT_FOUND: 'Usuario no encontrado',
  USER_EMAIL_NOT_FOUND: 'No se encontró el correo del usuario',
  USER_NOT_IN_ORG: 'El usuario no pertenece a la empresa seleccionada',
  PASSWORD_TOO_SHORT: 'La contraseña debe tener al menos 6 caracteres',
  FETCH_RECEIPTS: 'No se pudieron cargar los vouchers',
  FETCH_RECEIPTS_SUMMARY: 'No se pudo cargar el resumen de vouchers',
  FETCH_RECEIPTS_SUMMARY_BY_DATE: 'No se pudo cargar el resumen de vouchers por fecha',
  FETCH_IMAGE: 'No se pudo cargar la imagen',
  CREATE_USER: 'No se pudo crear el usuario',
  CREATE_PROFILE: 'No se pudo crear el perfil',
  SAVE_PROFILE: 'No se pudo guardar el perfil',
  VALIDATE_INVITATION: 'No se pudo validar la invitación',
  FINALIZE_INVITATION: 'No se pudo finalizar la invitación',
  COMPLETE_INVITE: 'No se pudo completar la invitación',
  SEND_INVITATION: 'No se pudo enviar la invitación',
  LOAD_INVITATIONS: 'No se pudieron cargar las invitaciones',
  DELETE_INVITATION: 'No se pudo eliminar la invitación',
  BULK_CREATE_USERS: 'No se pudo completar la carga masiva de usuarios',
  VALIDATE_USER_PROFILE: 'No se pudo validar el perfil del usuario',
  CLEANUP_USER: 'No se pudieron limpiar los registros del usuario',
  DELETE_AUTH_USER: 'No se pudo eliminar el usuario de autenticación',
  PASSWORD_SETUP_LINK: 'No se pudo generar el enlace para configurar la contraseña',
  PASSWORD_SETUP_EMAIL: 'No se pudo enviar el correo para configurar la contraseña',
  PASSWORD_RESET_LINK: 'No se pudo generar el enlace para restablecer la contraseña',
  PASSWORD_RESET_EMAIL: 'No se pudo enviar el correo para restablecer la contraseña',
  SUPERADMIN_CREATE_ORGS: 'Solo el superadmin puede crear empresas',
  SUPERADMIN_UPDATE_STATUS: 'Solo el superadmin puede actualizar el estado',
  USER_LIMIT_REACHED: 'Se alcanzó el límite de usuarios del plan contratado',
  ORG_INACTIVE: 'La empresa está inactiva',
  SUBSCRIPTION_EXPIRED: 'La suscripción de la empresa ha vencido',
  NO_AUTH_USER: 'No se encontró un usuario autenticado',
  SERVER_CONFIG: 'Configuración del servidor incompleta',
} as const;
